### ISSUE TITLE
It keeps asking for captcha

### ISSUE THREAD

**Issue by hickop** [jgeboski/bitlbee-steam#76] opened 2015-03-01 09:20 UTC
Cannot make bitlbee-steam to connect to my steam account. It keeps re-asking for captcha and did not ask for authcode, no mail received with authcode either.
```
10:09 @hickop account steam on
10:09   @root steam - Logging in: Connecting
10:09   @root steam - Logging in: Requesting authentication key
10:09   @root steam - Logging in: Requesting authentication token
10:09   @root steam - Login error: Please verify your humanity by re-entering the characters below.
10:09   @root steam - Logging in: View: https://steamcommunity.com/public/captcha.php?gid=115177608879980027
10:09   @root steam - Logging in: Run: account steam set captcha <text>
10:09   @root steam - Logging in: Signing off..
10:11 @hickop account steam set captcha "CP@F7P"
10:11   @root steam - Logging in: Connecting
10:11   @root steam - Logging in: Requesting authentication key
10:11   @root captcha = `CP@F7P'
10:11   @root steam - Logging in: Requesting authentication token
10:11   @root steam - Login error: Please verify your humanity by re-entering the characters below.
10:11   @root steam - Logging in: View: https://steamcommunity.com/public/captcha.php?gid=115177608879986823
10:11   @root steam - Logging in: Run: account steam set captcha <text>
10:11   @root steam - Logging in: Signing off..
10:12 @hickop account steam set captcha "PFBJ3N"
10:12   @root steam - Logging in: Connecting
10:12   @root steam - Logging in: Requesting authentication key
10:12   @root captcha = `PFBJ3N'
10:12   @root steam - Logging in: Requesting authentication token
10:12   @root steam - Login error: Please verify your humanity by re-entering the characters below.
10:12   @root steam - Logging in: View: https://steamcommunity.com/public/captcha.php?gid=115177608879988014
10:12   @root steam - Logging in: Run: account steam set captcha <text>
10:12   @root steam - Logging in: Signing off..
```

**Comment by dgw** [comment] 2015-03-01 17:24
The CAPTCHA, I found when I got one, has to be requested from the same IP BitlBee is connecting from. In my case that meant wget/curl and a quick SFTP download from the server.

**Comment by promisedlandt** [comment] 2015-03-01 17:53
Good info, I just deleted / re-added my Steam account.

**Comment by hickop** [comment] 2015-03-01 18:01
Well I still can't figure it out. I'm using my web browser on the same machine as bitlbee server so it should have same IP address.
Tried to change client IP address in bitlbee.conf to match local and external IP, still no luck.
Sometimes it says Login error: Incorrect login.

**Comment by mkaito** [comment] 2015-05-16 01:51
I'm having this issue too. I'm checking the captcha from the same computer. My password contained some symbols, so I've changed it to something with only letters and numbers. I've also removed and re-added the steam account to bitlbee. Doesn't seem to work.

There's this conspicious `incorrect login` line though, which I can't figure out. I've double and triple checked that my credentials are configured correctly with the plugin.

    02:46 @mkaito account steam on
    02:46 @root steam - Logging in: Connecting
    02:46 @root steam - Logging in: Requesting authentication key
    02:46 @root steam - Logging in: Requesting authentication token
    02:46 @root steam - Login error: Please verify your humanity by re-entering the characters below.
    02:46 @root steam - Logging in: View: https://steamcommunity.com/public/captcha.php?gid=119688175311943534
    02:46 @root steam - Logging in: Run: account steam set captcha <text>
    02:46 @root steam - Logging in: Signing off..
    02:46 @mkaito account steam set captcha JTGWNZ
    02:46 @root steam - Logging in: Connecting
    02:46 @root steam - Logging in: Requesting authentication key
    02:46 @root captcha = `JTGWNZ'
    02:46 @root steam - Logging in: Requesting authentication token
    02:46 @root steam - Login error: Incorrect login.
    02:46 @root steam - Logging in: View: https://steamcommunity.com/public/captcha.php?gid=119688175311944746
    02:46 @root steam - Logging in: Run: account steam set captcha <text>
    02:46 @root steam - Logging in: Signing off..

**Comment by jgeboski** [comment] 2015-05-20 20:10
Others are also reporting similar issues, I am reopening for now.

**Comment by Contik** [comment] 2015-05-20 21:01
Oooh what a coincidence :) I was about to post in a separate issue. Same situation here. I can't seem to get past the captcha. My initial password had special characters so I ended up chaning it to a simpler one (16 characters with a random mix of digits and lowercase letters). Also disabled Steam Guard's e-mail notifications altough they weren't even triggered in the first place. Even without Steam Guard and with a simple password the situation's as follows.

```
DEBUG util: Reading file blist.xml from directory /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername
DEBUG prefs: Reading /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername/prefs.xml
DEBUG prefs: /purple/savedstatus/default changed, scheduling save.
DEBUG prefs: /purple/savedstatus/idleaway changed, scheduling save.
DEBUG prefs: /purple/savedstatus/isidleaway changed, scheduling save.
DEBUG prefs: /pidgin/plugins/loaded changed, scheduling save.
DEBUG prefs: Finished reading /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername/prefs.xml
DEBUG util: Writing file prefs.xml to directory /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername
DEBUG util: Writing file /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername/prefs.xml
DEBUG util: Writing file blist.xml to directory /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername
DEBUG util: Writing file /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername/blist.xml
DEBUG util: Writing file accounts.xml to directory /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername
DEBUG util: Writing file /home/myLocalUsername/bin/bitlbee/var/bitlbee//purple/myBitlbeeUsername/accounts.xml

[bitlbee-steam] POST Request (0x7ffff853b920): https://steamcommunity.com:443/mobilelogin/getrsakey/
[bitlbee-steam]   User-Agent: Steam App / BitlBee / 1.2.0
[bitlbee-steam]   Content-Length: 27
[bitlbee-steam]   Connection: Close
[bitlbee-steam]   Accept: */*
[bitlbee-steam]   Cookie: steamLogin=0%7C%7Coauth%3A%28null%29; sessionid=
[bitlbee-steam]   Host: steamcommunity.com
[bitlbee-steam]   Content-Type: application/x-www-form-urlencoded
[bitlbee-steam]
[bitlbee-steam]   username=mySteamUsername&donotcache=930

[bitlbee-steam] POST Response (0x7ffff853b920): https://steamcommunity.com:443/mobilelogin/getrsakey/ (200 OK)
[bitlbee-steam]   HTTP/1.1 200 OK
[bitlbee-steam]   Server: Apache
[bitlbee-steam]   Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' https://steamcommunity-a.akamaihd.net/ https://api.steampowered.com/ http://www.google-analytics.com https://ssl.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com; object-src 'none'; connect-src 'self' https://steamcommunity.com http://steamcommunity.com https://api.steampowered.com/; frame-src 'self' http://store.steampowered.com/ https://store.steampowered.com/ http://www.youtube.com https://www.youtube.com https://www.google.com;
[bitlbee-steam]   Expires: Mon, 26 Jul 1997 05:00:00 GMT
[bitlbee-steam]   Cache-Control: no-cache
[bitlbee-steam]   Content-Length: 658
[bitlbee-steam]   Content-Type: application/json; charset=utf-8
[bitlbee-steam]   Date: Wed, 20 May 2015 19:35:19 GMT
[bitlbee-steam]   Connection: close
[bitlbee-steam]   Set-Cookie: steamCountry=GB%7C85a4c528f41d7f62b061797760654468; path=/
[bitlbee-steam]
[bitlbee-steam]   {"success":true,"publickey_mod":"E3628710B4DB18BD026A3E5E69B6F630DD5A2F2C40F96055955D593660D8DB731250F41413D36262E5F50979601223ABE1102EE0CA19589752E9C422285443C90FC1DDBACEF248811AB4FD1EF80ABF9E9AB76F2DA1DEB4F81280ECD63D7B268D1121D45A789FEF6FE0CEDB9580101915B95E2AE0BA3FBE02A58B1310C814822000F4F7B2CC0C98CCC63B677FFF4F356B5839887CECA4AFE717830E3D4493DE9503DBD57F0208C604BACEF4519B0F6FD146958A6F262BA7600E6F328AB1B8A6196635761678EDD23AD88F1E8DF6A51C1C2F404CEE74757919B7079DB4C7EB326D8DB9140B34A9B1296B434D8409CBE49C2526993FA75A90099DD51B2D6FBDB52D","publickey_exp":"010001","timestamp":"72069650000","steamid":"12345678901234567","token_gid":"19938567ebaa000"}

[bitlbee-steam] POST Request (0x7ffff8294da0): https://steamcommunity.com:443/mobilelogin/dologin/
[bitlbee-steam]   User-Agent: Mozilla/5.0 (Android; Mobile; BitlBee) BitlBee/3.4 bitlbee-steam/1.2.0
[bitlbee-steam]   Content-Length: 602
[bitlbee-steam]   Connection: Close
[bitlbee-steam]   Accept: */*
[bitlbee-steam]   Cookie: steamLogin=0%7C%7Coauth%3A%28null%29; sessionid=
[bitlbee-steam]   Host: steamcommunity.com
[bitlbee-steam]   Content-Type: application/x-www-form-urlencoded
[bitlbee-steam]
[bitlbee-steam]   oauth_client_id=DE45CD61&emailauth=&captcha_text=&remember_login=true&password=mi0fWYmpyyySAvy8b3przU%2B8tDg4lXw%2F7PXaB6QlTGDxrFQlS%2Fl70vI3vEtrR7DlGt3%2FQHYWv9SzhsFWai4yip%2BXd6blJgLVEjyApKlKqXWcIIikEBqLcFuaVdZqqO6xkr0Bkw5bpSWOwT9735NYAfGJEJgb%2FiGUpNOmPm48tIObD4aFMEyQ8IwqwMg%2BqImZG6RNfK8lW4HNJwBPR9B1Oc%2BawaGA3dt%2B6wzauR4VW4rbtlyKpO5hVBvxjfqhZ7KNvrHjf8%2B26E1cTOAGtZRGf0RGVnEvK6dQhCPPZQlUGd%2FigJIXRCdaFcb%2B8uBDYRYTcyvspBU73p%2FH1EhUcL1ZHw%3D%3D&emailsteamid=&oauth_scope=read_profile%20write_profile%20read_client%20write_client&rsatimestamp=72069650000&username=mySteamUsername&donotcache=704&captchagid=

[bitlbee-steam] POST Response (0x7ffff8294da0): https://steamcommunity.com:443/mobilelogin/dologin/ (200 OK)
[bitlbee-steam]   HTTP/1.1 200 OK
[bitlbee-steam]   Server: Apache
[bitlbee-steam]   Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' https://steamcommunity-a.akamaihd.net/ https://api.steampowered.com/ http://www.google-analytics.com https://ssl.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com; object-src 'none'; connect-src 'self' https://steamcommunity.com http://steamcommunity.com https://api.steampowered.com/; frame-src 'self' http://store.steampowered.com/ https://store.steampowered.com/ http://www.youtube.com https://www.youtube.com https://www.google.com steammobile://*;
[bitlbee-steam]   Expires: Mon, 26 Jul 1997 05:00:00 GMT
[bitlbee-steam]   Cache-Control: no-cache
[bitlbee-steam]   Content-Length: 178
[bitlbee-steam]   Content-Type: application/json; charset=utf-8
[bitlbee-steam]   Date: Wed, 20 May 2015 19:35:20 GMT
[bitlbee-steam]   Connection: close
[bitlbee-steam]   Set-Cookie: steamCountry=GB%7C85a4c528f41d7f62b061797760654468; path=/
[bitlbee-steam]
[bitlbee-steam]   {"success":false,"message":"Please verify your humanity by re-entering the characters below.","requires_twofactor":false,"captcha_needed":true,"captcha_gid":"218768001046947395"}
[bitlbee-steam] Error: Please verify your humanity by re-entering the characters below.

[bitlbee-steam] POST Request (0x7ffff8549470): https://steamcommunity.com:443/mobilelogin/getrsakey/
[bitlbee-steam]   User-Agent: Steam App / BitlBee / 1.2.0
[bitlbee-steam]   Content-Length: 27
[bitlbee-steam]   Connection: Close
[bitlbee-steam]   Accept: */*
[bitlbee-steam]   Cookie: steamLogin=0%7C%7Coauth%3A%28null%29; sessionid=
[bitlbee-steam]   Host: steamcommunity.com
[bitlbee-steam]   Content-Type: application/x-www-form-urlencoded
[bitlbee-steam]
[bitlbee-steam]   username=mySteamUsername&donotcache=336

[bitlbee-steam] POST Response (0x7ffff8549470): https://steamcommunity.com:443/mobilelogin/getrsakey/ (200 OK)
[bitlbee-steam]   HTTP/1.1 200 OK
[bitlbee-steam]   Server: Apache
[bitlbee-steam]   Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' https://steamcommunity-a.akamaihd.net/ https://api.steampowered.com/ http://www.google-analytics.com https://ssl.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com; object-src 'none'; connect-src 'self' https://steamcommunity.com http://steamcommunity.com https://api.steampowered.com/; frame-src 'self' http://store.steampowered.com/ https://store.steampowered.com/ http://www.youtube.com https://www.youtube.com https://www.google.com;
[bitlbee-steam]   Expires: Mon, 26 Jul 1997 05:00:00 GMT
[bitlbee-steam]   Cache-Control: no-cache
[bitlbee-steam]   Content-Length: 658
[bitlbee-steam]   Content-Type: application/json; charset=utf-8
[bitlbee-steam]   Date: Wed, 20 May 2015 19:36:16 GMT
[bitlbee-steam]   Connection: close
[bitlbee-steam]   Set-Cookie: steamCountry=GB%7C85a4c528f41d7f62b061797760654468; path=/
[bitlbee-steam]
[bitlbee-steam]   {"success":true,"publickey_mod":"E3628710B4DB18BD026A3E5E69B6F630DD5A2F2C40F96055955D593660D8DB731250F41413D36262E5F50979601223ABE1102EE0CA19589752E9C422285443C90FC1DDBACEF248811AB4FD1EF80ABF9E9AB76F2DA1DEB4F81280ECD63D7B268D1121D45A789FEF6FE0CEDB9580101915B95E2AE0BA3FBE02A58B1310C814822000F4F7B2CC0C98CCC63B677FFF4F356B5839887CECA4AFE717830E3D4493DE9503DBD57F0208C604BACEF4519B0F6FD146958A6F262BA7600E6F328AB1B8A6196635761678EDD23AD88F1E8DF6A51C1C2F404CEE74757919B7079DB4C7EB326D8DB9140B34A9B1296B434D8409CBE49C2526993FA75A90099DD51B2D6FBDB52D","publickey_exp":"010001","timestamp":"72069650000","steamid":"12345678901234567","token_gid":"19938567ebaa000"}

[bitlbee-steam] POST Request (0x7ffff856f920): https://steamcommunity.com:443/mobilelogin/dologin/
[bitlbee-steam]   User-Agent: Mozilla/5.0 (Android; Mobile; BitlBee) BitlBee/3.4 bitlbee-steam/1.2.0
[bitlbee-steam]   Content-Length: 632
[bitlbee-steam]   Connection: Close
[bitlbee-steam]   Accept: */*
[bitlbee-steam]   Cookie: steamLogin=0%7C%7Coauth%3A%28null%29; sessionid=
[bitlbee-steam]   Host: steamcommunity.com
[bitlbee-steam]   Content-Type: application/x-www-form-urlencoded
[bitlbee-steam]
[bitlbee-steam]   oauth_client_id=DE45CD61&emailauth=&captcha_text=%25RXMJA&remember_login=true&password=L5wgWracMj5lJ49UljkiQswpa2n6xJQek6n%2BL%2B777TNQf%2FLfRMBWvSaU76ZAxGURumtYIMmett%2FBZldwVkCXrGC9%2BoQk64x9RIGAMsYWu6Z4o5PU%2BcR9S0pqVy0E0HwOK6QNeQwghJRUQLQyt9UzpQbjTW8YWUTV7tIEy0mE3fNFQg%2FktjcfWHtNssmCoh0XlYHzBnBF7rPvx9uPXczb1I%2Fq%2FqNnk%2FkVxdDqeOabWxJV6zrwvIAQLwiwzX%2BDr7dz%2FSZ0xx3GorokBqhosoAoszboJPJl%2FnOXaUyS13kbWoPO2A45lj%2FoRW87Y3RFLyUZzkarbyAQr51X%2B9sLzveqeQ%3D%3D&emailsteamid=&oauth_scope=read_profile%20write_profile%20read_client%20write_client&rsatimestamp=72069650000&username=mySteamUsername&donotcache=214&captchagid=218768001046947395

[bitlbee-steam] POST Response (0x7ffff856f920): https://steamcommunity.com:443/mobilelogin/dologin/ (200 OK)
[bitlbee-steam]   HTTP/1.1 200 OK
[bitlbee-steam]   Server: Apache
[bitlbee-steam]   Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' https://steamcommunity-a.akamaihd.net/ https://api.steampowered.com/ http://www.google-analytics.com https://ssl.google-analytics.com https://www.google.com https://www.gstatic.com https://apis.google.com; object-src 'none'; connect-src 'self' https://steamcommunity.com http://steamcommunity.com https://api.steampowered.com/; frame-src 'self' http://store.steampowered.com/ https://store.steampowered.com/ http://www.youtube.com https://www.youtube.com https://www.google.com steammobile://*;
[bitlbee-steam]   Expires: Mon, 26 Jul 1997 05:00:00 GMT
[bitlbee-steam]   Cache-Control: no-cache
[bitlbee-steam]   Content-Length: 130
[bitlbee-steam]   Content-Type: application/json; charset=utf-8
[bitlbee-steam]   Date: Wed, 20 May 2015 19:36:17 GMT
[bitlbee-steam]   Connection: close
[bitlbee-steam]   Set-Cookie: steamCountry=GB%7C85a4c528f41d7f62b061797760654468; path=/
[bitlbee-steam]
[bitlbee-steam]   {"success":false,"requires_twofactor":false,"captcha_needed":true,"captcha_gid":"218768001046949793","message":"Incorrect login."}
[bitlbee-steam] Error: Incorrect login.
```

**Comment by jgeboski** [comment] 2015-05-20 22:00
This appears to be out of the control of this plugin.  While I am able to recreate this issue within the plugin, I can also recreate it by attempting to login to the Steam website(s).  Unfortunately, all we can do for now is wait.

**Comment by xxami** [comment] 2015-05-21 15:09
is there a workaround? i'm having the same issue and can not log in to any of my accounts regardless of steam guard status and password complexity - although i can log in using the steam website, and my phone :cat:

**Comment by Tmplt** [comment] 2015-05-27 12:24
I seem to have a similar issue, but I am prompted with "Incorrect login" even thought I *have* entered the right password and user name. Am I right in adding the account like this: `account add <steam-login-name> <steam-passwd>`? I lack experience with `bitlbee`, unfortunately.

I do run the `bitlbee`-server on a VPS, though, I have yet to try running the same thing locally. I'll try that later today.

**Comment by sid3windr** [comment] 2015-05-27 15:07
Same issue here (with the debian package), getting incorrect login.

**Comment by Cpuroast** [comment] 2015-05-27 15:10
yup, same here, seems like a steam issue

**Comment by mkaito** [comment] 2015-05-28 00:38
Maybe they've changed something on their end. Because I can log into the steam client and website just fine.

**Comment by jgeboski** [comment] 2015-05-28 02:28
This has been fixed as of 854e7e3.

**Closed by jgeboski** 2015-05-28 02:28 UTC
Labels: bug

**Comment by Hund** [comment] 2015-08-17 22:12
I have the same issue. :(

**Comment by Hund** [comment] 2016-06-21 07:50
I still have this issue.

**Comment by ErikUri** [comment] 2016-06-28 09:43
There's been a regression; I'm running into this issue as well. I also have a password with many different types of characters, although I was unable to test changing my password to resolve the issue.
